services:
    client:
        build: ./client
        volumes:
            - client-build:/dist

    server:
        build: ./server
        environment:
            - SECRET_KEY=yout_secret_key
            - DATABASE_URI=mysql+pymysql://root@mysql/db_users
        depends_on:
            - mysql

    mysql:
        image: mysql:8
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db_users
        volumes:
            - db_data:/lib/mysql

    nginx:
        image: nginx:alpine
        ports:
            - '3000:80'
        volumes:
            - client-build:/usr/share/nginx/html
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - client
            - server

volumes:
    client-build:
    db_data:
